# Generated by Django 4.1.7 on 2023-05-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_name',
            field=models.CharField(max_length=255),
        ),
    ]
