# Generated by Django 4.1.7 on 2023-05-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_student_academic_year_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='datee',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
