# Generated by Django 4.1.7 on 2023-05-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_datee_attendance_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='roll_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
