# Generated by Django 4.1.7 on 2023-05-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_student_address_student_brach_student_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='brach',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('MEC', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
