# Generated by Django 4.1.7 on 2023-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_student_brach_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('MEC', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1SEM', '1th sem'), ('1SEM', '2th sem'), ('1SEM', '3th sem'), ('1SEM', '4th sem'), ('1SEM', '5th sem'), ('1SEM', '6th sem'), ('1SEM', '7th sem'), ('1SEM', '8th sem')], max_length=20),
        ),
    ]
