# Generated by Django 4.1.7 on 2023-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_student_branch_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1SEM', '1st sem'), ('1SEM', '2nd sem'), ('1SEM', '3rd sem'), ('1SEM', '4th sem'), ('1SEM', '5th sem'), ('1SEM', '6th sem'), ('1SEM', '7th sem'), ('1SEM', '8th sem')], max_length=20),
        ),
    ]
