# Generated by Django 4.1.7 on 2023-05-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_student_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='class_name',
            new_name='subject_code',
        ),
    ]
