# Generated by Django 4.1.7 on 2023-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_rename_class_name_attendance_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='academic_year',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.CharField(choices=[('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('MEC', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.CharField(choices=[('1SEM', '1st sem'), ('2SEM', '2nd sem'), ('3SEM', '3rd sem'), ('4SEM', '4th sem'), ('5SEM', '5th sem'), ('6SEM', '6th sem'), ('7SEM', '7th sem'), ('8SEM', '8th sem')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1SEM', '1st sem'), ('2SEM', '2nd sem'), ('3SEM', '3rd sem'), ('4SEM', '4th sem'), ('5SEM', '5th sem'), ('6SEM', '6th sem'), ('7SEM', '7th sem'), ('8SEM', '8th sem')], max_length=20),
        ),
    ]
