# Generated by Django 4.1.7 on 2023-05-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendance_academic_year_attendance_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='semester',
            new_name='semister',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='semester',
            new_name='semister',
        ),
    ]
