# Generated by Django 4.1.7 on 2023-05-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_rename_phone_number_ia_marks_ia_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ia_one',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ia_three',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ia_two',
        ),
    ]
