# Generated by Django 4.1.7 on 2023-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_remove_student_ia_one_remove_student_ia_three_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ia_marks',
            old_name='name',
            new_name='student',
        ),
        migrations.AddField(
            model_name='ia_marks',
            name='subject_code',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
