# Generated by Django 4.1.7 on 2023-05-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_rename_name_ia_marks_student_ia_marks_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ia_marks',
            name='datee',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ia_marks',
            name='roll_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
