# Generated by Django 4.1.7 on 2023-05-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_ia_marks_datee_ia_marks_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ia_marks',
            name='semester',
        ),
    ]
