# Generated by Django 4.1.7 on 2023-05-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_remove_ia_marks_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ia_marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
    ]
