# Generated by Django 4.1.7 on 2023-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_alter_ia_marks_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ia_marks',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
