# Generated by Django 4.1.7 on 2023-05-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_ia_marks_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ia_marks',
            name='datee',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ia_marks',
            name='ia_one',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ia_marks',
            name='ia_three',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ia_marks',
            name='ia_two',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ia_marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
    ]
