# Generated by Django 4.1.7 on 2023-05-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_alter_ia_marks_datee_alter_ia_marks_ia_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ia_marks',
            name='datee',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ia_marks',
            name='ia_one',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ia_marks',
            name='ia_three',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ia_marks',
            name='ia_two',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ia_marks',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
